definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: test_user_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: assessments
    mysql:
      image: mysql
      variables:
        MYSQL_DATABASE: test_cms_db
        MYSQL_ROOT_PASSWORD: assessments

  caches:
    nodemodules: ./node_modules
  
  scripts:
    - script: 
      - &skip-bitbucket-authored-commits
        '[[ $(git log -1 --pretty=%an) == "bitbucket-pipelines" ]] && echo "Commit author is bitbucket-pipelines - exiting Pipeline" && exit 0'

    - script: &docker-build-and-push-to-aws
      - pip3 install -U awscli

      - export BRANCH_TAG=$(echo "$BITBUCKET_BRANCH" | sed -E 's/([^0-9a-zA-Z]+)/-/g' | awk '{print tolower($0)}')
      - export REPO=$DOCKER_REPO_URL/kidsloop-assessment # DOCKER_REPO_URL is workspace wide variable
      - export COMMIT_TAG=$(echo $BITBUCKET_COMMIT | cut -c1-7)
      - printf '"Git tag":"%s", "Git branch":"%s", "Git commit":"%s" "ECR repo":"%s"' $BITBUCKET_TAG $BRANCH_TAG $COMMIT_TAG $REPO

      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $DOCKER_REPO_URL

      - docker build -t kidsloop-assessment .
      - docker tag kidsloop-assessment:latest $REPO:$BITBUCKET_TAG'
      - docker tag kidsloop-assessment:latest $REPO:$BRANCH_TAG
      - docker tag kidsloop-assessment:latest $REPO:$BRANCH_TAG-latest
      - docker tag kidsloop-assessment:latest $REPO:$BRANCH_TAG-$BITBUCKET_BUILD_NUMBER
      - docker tag kidsloop-assessment:latest $REPO:$BRANCH_TAG-$COMMIT_TAG

      - docker push $REPO:$BITBUCKET_TAG'
      - docker push $REPO:$BRANCH_TAG
      - docker push $REPO:$BRANCH_TAG-latest
      - docker push $REPO:$BRANCH_TAG-$BITBUCKET_BUILD_NUMBER
      - docker push $REPO:$BRANCH_TAG-$COMMIT_TAG

  steps:
    - step: &npm-install-and-test
        name: 'Build and test'
        image: node:lts
        services:
          - postgres
          - mysql
        script:
          - *skip-bitbucket-authored-commits
          - export HUSKY=0
          - npm i
          - TEST_POSTGRES_PORT=5432 TEST_MYSQL_PORT=3306 npm run test:codecov
        caches:
          - nodemodules
        artifacts:
          - node_modules/**

    - step: &docker-build
        name: 'Docker build'
        services:
          - docker
        script:
          - *skip-bitbucket-authored-commits
          - docker build -t kidsloop-assessment .
  
    - step: &version-release
        name: 'Release Version Bump'
        image: node:16
        caches:
        - nodemodules
        script:
          - *skip-bitbucket-authored-commits
          - if [[ $BITBUCKET_BRANCH != master ]]; then echo "This can only be performed on master branch" && exit 1; fi

          - npm run release
          - export VERSION_TAG=$(git describe --tags)
          - 'echo "New release version: $VERSION_TAG - $(git log -1 --pretty=%h%B)"'
          - export TAG_EXISTS=$(git ls-remote origin refs/tags/$VERSION_TAG)
          - '[[ ! -z "$TAG_EXISTS" ]] && echo "$VERSION_TAG already exists" && exit 1'
          # - '[[ ! -z "$TAG_EXISTS" ]] && echo "Delete remote tag $VERSION_TAG" && git push --delete origin "$VERSION_TAG"'
          - git push origin master
          - git push origin --tags

    - step: &slack-notification-version-release
        name: '🔔 Slack: Version Release'
        script:
          - *skip-bitbucket-authored-commits
          - pipe: atlassian/slack-notify:1.0.1
            variables:
              WEBHOOK_URL: $SLACK_WEBHOOK
              MESSAGE: 'A new version of Assessment Service ($BITBUCKET_COMMIT) has been merged into $BITBUCKET_BRANCH'

    - step: &slack-notification-build
        name: '🔔 Slack: Build'
        script:
          - *skip-bitbucket-authored-commits
          - pipe: atlassian/slack-notify:1.0.1
            variables:
              WEBHOOK_URL: $SLACK_WEBHOOK
              MESSAGE: 'A new build of Assessment Service ($BITBUCKET_TAG) has been pushed to ECR'

pipelines:
  pull-requests:
    '**': # This runs as default for any branch not elsewhere defined.:
      - step:
          name: 'Conventional Commits check'
          image: node:lts
          script:
            - /bin/bash commitlint-pipeline-check.sh
      - step: *npm-install-and-test
      - step: *docker-build

  branches:
    master:
      - step: *npm-install-and-test
      - step: *docker-build
      - step: *version-release
      - step: *slack-notification-version-release

  tags:
    '*':
      - step:
          name: 'Docker build + push to ECR'
          deployment: release
          image: python:3.9-alpine
          services:
            - docker
          script: *docker-build-and-push-to-aws
      - step: *slack-notification-build
